# Generated by Django 2.2 on 2020-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='author',
            field=models.TextField(max_length=1024),
        ),
    ]
